import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://www.aashik.dev/",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 1.0,
    },
    {
      url: "https://www.aashik.dev/blogs",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/trendblog/base-volume-booster",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/product/solana-volume-booster",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/product/base-volume-booster",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/product/ton-volume-booster",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/product/holders-increase-bot",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/product/Moonshot-Volume-Booster",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/product/solana-sniper-bot",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/service/DEXtools-Trending-Tools-Development",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/service/Smart-Contract-Develop",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/service/Smart-Contract-Audit",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/service/Telegram-Bot-Development",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/service/TON-App-Development",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/service/Solana-Development",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.8,
    },
    {
      url: "https://www.aashik.dev/blog/why-our-solana-dex-volume-bot-is-the-ultimate-tool-for-traders",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/maximizing-solana-token-visibility-with-the-solana-volume-booster",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/how-to-effectively-use-solana-volume-bots-to-attract-investors",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/boost-your-tokens-performance-on-raydium-with-our-volume-booster",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/a-comprehensive-guide-to-jupiter-volume-boosting-bots-for-token-creators",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/increase-your-tokens-market-impact-with-pumpfun-volume-boosters-introduction",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/strategies-to-enhance-liquidity-and-volume-on-solana",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/unlocking-the-power-of-raydium-volume-boosting-for-token-growth",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/why-every-solana-developer-needs-a-volume-boosting-bot",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/how-to-create-a-liquidity-pool-in-solana-a-step-by-step-guide",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/adding-liquidity-to-jupiter-essential-tips-for-token-creators",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/effective-tactics-to-increase-pumpfun-liquidity-and-attract-investors",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/defi-and-solana-leveraging-volume-boosters-for-enhanced-token",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/how-to-trend-on-dextools-strategies-for-solana-tokens",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/mastering-coinmarketcap-boosting-your-token-with-effective-tools",
      lastModified: new Date("2024-07-24T16:59:23+00:00"),
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/navigating-dexscreener-techniques-to-increase-token-visibility",
      lastModified: "2024-07-24T16:59:23+00:00",
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/how-to-list-your-solana-token-for-maximum-impact",
      lastModified: "2024-07-24T16:59:23+00:00",
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/solana-web3-development-enhancing-token-volume-with-advanced-tools",
      lastModified: "2024-07-24T16:59:23+00:00",
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/essential-tools-for-solana-token-creators-a-guide-to-boosting-volume",
      lastModified: "2024-07-24T16:59:23+00:00",
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/how-to-boost-your-token-on-raydium-insider-tips-and-tricks",
      lastModified: "2024-07-24T16:59:23+00:00",
      changeFrequency: "yearly",
      priority: 0.64,
    },
    {
      url: "https://www.aashik.dev/blog/the-ultimate-guide-to-boosting-solana-token-volume-and-liquidity",
      lastModified: "2024-07-24T16:59:23+00:00",
      changeFrequency: "yearly",
      priority: 0.64,
    },
  ];
}
